# Inside the DST: Initial Load and Configure
To begin a scenario run of implemented management actions in the DST, begin by generating the `InputList` with either the Excel input spreadsheet ([Saved .csv File]) or within the R code ([Create List of Actions]) and configuring the user options. The flow chart below describes the process the model takes for implementing management actions, specifically which actions affect various gear quantifications and modifications.

![The DST model has a modular design made up of various fishery and whale inputs (in dark blue), with a number of submodels (light blue headers) used to carry out calculations and transformations that are imposed by management actions (white exterior arrows) that eventually lead to resulting risk estimates.](images/FlowChart012723-04.png)

## Read Input List
The DST identifies all model run variables that have been specified and assigns default values for those that have not been specified. A subfolder is generated (if it doesn't already exist from a previous duplicated run). In our example from the above section, [InputActions], the subfolder is named 'ScenarioName.' The DST determines the structure of InputActions (the .csv file or R list) and begins unlisting the provided InputActions.

## Load Data
The DST then loads in the following data inputs:

 - Fishery Input Layer
 - Whale Density Layer
 - Whale Vertical Distribution Layer
 - Whale Body Dimensions
 - Threat Model

If any of these input files do not exist in the expected directory, the model will end and report an error that the specified file was not found. The model also checks for the four required elements within the fishery input layer (GearMap, GearPerString, CumulativeEffort, and LineStrength). Any missing shapefiles specified in the `InputActions` (Table \@ref(tab:aco)) will also prevent the DST from moving on to model calculation stages.
